### ISSUE TITLE
Join operation is not working after update to 1.2.0

### ISSUE THREAD

**Issue by alexandraprisecaru** [LGouellec/kafka-streams-dotnet#113]
Hello,

We are currently using the Streamiz package in our project. We are using it mainly for joining streams in a .NET 6 microservice.

I updated to the latest package version to benefit from the Schema Registry integration, but the join operation is no longer working.

Initially, it was failing because it didn't have a replication factor of 3. I set that in the stream config and then the console logs looked fine, but the join operation was not applied.

I set the log level to debug and attached the logs here. Were there any major changes between the two versions in this area?
[streamiz_update_1.2.0_logs.txt](https://github.com/confluentinc/kafka-streams-examples/files/8317936/streamiz_update_1.2.0_logs.txt.txt)[](https://user-images.githubusercontent.com/33525209/159305190-b062d32b-2ece-4b2e-8afb-337608b62e2d.png)

Also, I noticed that after the update it auto-creates topics. It also adds additional topics for other operations such as SelectKey.
![image](https://user-images.githubusercontent.com/33525209/160348025-1196333c-074c-49d0-a49e-4dc41254512c.png)

This didn't happen before. Is there any way we could disable this, but keep the code up & running?
I set the AllowAutoCreateTopics property to false, but it didn't help.

Any help is much appreciated! :)
Thanks!

**Comment by alexandraprisecaru** [comment]
[](https://user-images.githubusercontent.com/33525209/159683932-6919b2b0-5601-416d-ae4b-b10e1023abe5.png)[](https://user-images.githubusercontent.com/33525209/159685387-9fcec1d6-4dd2-405e-beec-edd4a52db356.png)One more question, sorry for the trouble.

I noticed that if I use the SchemaAvroSerDes I am forced to use a value type or an object that implements ISpecificRecord or inherits SpecificFixed. This means, that for my models I need to attach the Schema even though I am communicating with Schema Registry.
![image](https://user-images.githubusercontent.com/33525209/160348184-0c872681-5757-4277-b79d-974b6e0c8ee0.png)

In my implementation of SerDes I skipped this step by using Chr.Avro.Confluent serializer & deserializer.
![image](https://user-images.githubusercontent.com/33525209/160348223-5c88dcc5-6cab-44e3-af84-c768a01c9a65.png)

Would it be possible for the Streamiz SerDes to have this integrated somehow at one point?
I think it would be very useful to rely only on Schema Registry for data governance.

Thanks!

**Comment by LGouellec** [comment]
> Hello,
> 
> We are currently using the Streamiz package in our project. We are using it mainly for joining streams in a .NET 6 microservice.
> 
> I updated to the latest package version to benefit from the Schema Registry integration, but the join operation is no longer working.
> 
> Initially, it was failing because it didn't have a replication factor of 3. I set that in the stream config and then the console logs looked fine, but the join operation was not applied.
> 
> I set the log level to debug and attached the logs here. Were there any major changes between the two versions in this area? [streamiz_update_1.2.0_logs.txt](https://github.com/confluentinc/kafka-streams-examples/files/8317936/streamiz_update_1.2.0_logs.txt.txt)
> 
> Also, I noticed that after the update it auto-creates topics. It also adds additional topics for other operations such as SelectKey. ![image](https://user-images.githubusercontent.com/33525209/160348025-1196333c-074c-49d0-a49e-4dc41254512c.png)
> 
> This didn't happen before. Is there any way we could disable this, but keep the code up & running? I set the AllowAutoCreateTopics property to false, but it didn't help.
> 
> Any help is much appreciated! :) Thanks!

Hi @alexandraprisecaru, 

Since 1.2.0 release, we backup local state store with a changelog topic. The same behavior exist with Kafka Streams JAVA to persist the state store on a topic in case of your local instance crash. 
For more information, [see here](https://developer.confluent.io/learn-kafka/kafka-streams/stateful-fault-tolerance/)

Unfortunately, there is a fatal bug on 1.2.0 about infinite restoration from changelog topic. This bug is track [here](https://github.com/LGouellec/kafka-streams-dotnet/issues/103).
Please use 1.2.2 release to avoid any bug on this part.

Regards,

**Comment by alexandraprisecaru** [comment]
Hi @LGouellec , thanks for responding so fast! 🚀 
Thanks for the info, it was very helpful!

Sorry, I forgot to mention that it stopped working for me from the 1.2.0 version, but I've mainly been testing with 1.2.2 and it's still not working for me.

I cloned the repo and applied my changes for serialization and deserialization using Chr.Avro and that seems to work fine. 
However, I identified a place where it crashes.

I have a small wrapper over the Join function as follows:
![image](https://user-images.githubusercontent.com/33525209/160602403-c0e5ba1e-a8bc-4d7f-9197-7bc378e17d99.png)

When I don't pass the join props variable, it doesn't crash, but it doesn't join either.

When I pass the join props it fails at serialization, because the SerDes is not initialized ("SchemaSerDes<{typeof(T).Name}> is not initialized !")
This happens when the serializer is called from the WrappedWindowStore class.
![image](https://user-images.githubusercontent.com/33525209/160603293-958173a5-b915-4c12-90c1-91892f199242.png)

I noticed that in the join process it initializes the serdes, but not all of them I think..
![image](https://user-images.githubusercontent.com/33525209/160612362-72b3321a-7a5d-4430-a22a-9bbb5dbf94b1.png)
![image](https://user-images.githubusercontent.com/33525209/160612709-fbb5707e-c28c-4b16-a151-4f55ed564883.png)


I'm still not very familiar with the code, but I'll try to find a solution.

Any help is much appreciated 😃

**Comment by alexandraprisecaru** [comment]
I tried initializing the key serdes and value serdes from the WrappedWindowStore constructor using the correct config just for testing. 
Now it doesn't fail because of initialization errors and serialization and deserialization are called every time I am sending data on the topics I want to join. I get good data on serialization and deseriailzation.

Snippets from the SchemaSerDes class:
![image](https://user-images.githubusercontent.com/33525209/160620658-b3c46cfd-d92b-4c17-a3ce-17ea7a42ca12.png)

![image](https://user-images.githubusercontent.com/33525209/160620814-be2a51d8-3527-4e4d-a298-baaa2a6a9aeb.png)

However, the join result still doesn't reach my end topic...

**Comment by LGouellec** [comment]
Hi @alexandraprisecaru,

I create a reproducer about your usecase. Join 2 topics using Avro serdes in value and it works fine. 
Join process is correct and publish records into the sink topic.

You can run this demo using `start.sh`. 

Can you just forks my repo and create your own branch with your fix (modification) to see how is the fix ? where is the fix and so on ...

Thanks for your help 👍 🥇 

Regards,
