### ISSUE TITLE
SessionWindows support

### ISSUE THREAD

**Issue by michaeljurek-ext95167** [LGouellec/kafka-streams-dotnet#133]
Hello,
I noticed, there is no support for SessionWindow. I looked at the source code and it seems that at least some preparation has been done (such as ISessionStore<K,AGG>). Is there any chance this would be implemented in a foreseeable future?
I might try by myself but I wonder if there is any special reason behind this... are there any dangerous traps that can catch me?
Thanks a lot and have a nice day,
Michael

**Comment by LGouellec** [comment]
Hi @michaeljurek-ext95167,

True, I began some background code for session store feature. But it's not complete at all.

Session store is a windowing store with different behavior.

You can have a look at Kafka streams in JAVA if you want and trying to implement this feature if you want.

If you have any questions feel free to reach out to me.

Kr

**Comment by michaeljurek-ext95167** [comment]
Thanks for your answer. So if I understand you correctly, SessionWindow just did not make it high enough on priority list and there is no technical reason for not implementing it so far.
Thanks and have a nice day,
Michael

**Comment by LGouellec** [comment]
Hi @michaeljurek-ext95167, 

No technical reason for not implementing. Just need more free time 😅.

++

**Comment by douglasg14b** [comment]
Was this closed because it as Completed, or closed because it will not be done?

**Comment by LGouellec** [comment]
Closed because for now it was not planned on the roadmap.
