### ISSUE TITLE
Getting Window Final Results

### ISSUE THREAD

**Issue by 1995liuwei** [LGouellec/kafka-streams-dotnet#134]
Is it possible to get window final result in Kafka Streams by suppressing the intermediate results. 

There is my code
                builder
                .GroupBy((key, value) => value)
                .WindowedBy(TumblingWindowOptions.Of(TimeSpan.FromSeconds(5)))
                .Count(InMemoryWindows<string, long>.As("store"))
                .ToStream()
                .Map((window, count) => new KeyValuePair<string, string>(window.Key, count.ToString()))
                //.To("test_count")
                .Foreach((key, value) =>
                {
                    Console.WriteLine($"{key}出现了{value}次");
                }); 

I just want the final result，but the intermediate results will appear.
I would be really appreciate for your reply.

**Comment by LGouellec** [comment]
Hi @1995liuwei,

Unfortunately, Suppress(..) processor is not available yet (It's in my todo list).

I hope in next release (perhaps 1.4 or 1.5). Feel free to contribute if you want.

**Comment by 1995liuwei** [comment]
> appreciate

Thank you for your reply.
