### ISSUE TITLE
Ability to pass in KeySerDes and ValueSerDes into the .To(...) function

### ISSUE THREAD

**Issue by cacodev** [LGouellec/kafka-streams-dotnet#136]
Description
===========
I am building a complex stream where I am rekeying, and joining two topics.  When I do the `.To("topic-name")` operation, I want to be able to pass in a custom serdes for the key and value. ex:

`.To("topic-name", keySerDes, valueSerDes);`

Or, be able to pass in a `Produced<K, V>`  parameter. The java api's have this functionality (ref: [Apache Kafka KStream](https://kafka.apache.org/26/javadoc/org/apache/kafka/streams/kstream/KStream.html#to-java.lang.String-org.apache.kafka.streams.kstream.Produced-)

I can submit a PR for these changes if you can advise which option you would prefer.

**Comment by LGouellec** [comment]
Hi @cacodev,

Thanks for your issue.

As the [consumer side ](https://github.com/LGouellec/kafka-streams-dotnet/blob/b3f2f9b98d9617a205fedf4adfe4b2685e5d68ff/core/StreamBuilder.cs#L67), I prefer this approach :
``` csharp
.To("topic-name", keySerDes, valueSerDes);
```

Feel free to create a PR

Thanks for your contribution

**Comment by LGouellec** [comment]
PR Merged
