### ISSUE TITLE
External call inside topology

### ISSUE THREAD

**Issue by LGouellec** [LGouellec/kafka-streams-dotnet#147]
Description
===========

If you have already built a Kafka Streams application and you had to call an external service or database in the middle of one of your topologies, you've probably faced some issues if that call takes too long which can drive your stream processing application in serious troubles and most likely your overall system in some kind of snowball effect. If not (or not yet 😉), your application is prone such issues and you should be aware about that.

It's true with JAVA implementation but also in another way with librdkafka based clients.

```
max.poll.interval.ms = 300000
```

The aims of this purpose is to allow execute external async call inside your Streamiz topology.

![280950129_725742468568986_2513486809243885186_n](https://user-images.githubusercontent.com/3295357/170827130-15fc094d-b9d6-4101-b5f3-ead892f3ce2a.jpeg)

**Comment by LGouellec** [comment]
# Follow-up


Regarding this topology : 
``` csharp
builder
                .Stream<string, string>("input")
                .ExternalCallAsync(
                    async (record, context) =>
                        await Task.FromResult(new KeyValuePair<string, string>(record.Key, record.Value)),
                    RetryPolicyBuilder
                        .NewBuilder()
                        .NumberOfRetry(10)
                        .RetryBackOffMs(100)
                        .Build())
                .MapValues((k,v) => v.ToUpper())
                .To("output");
```

Here the DAG of this topology, 
``` log
Topologies:
   Sub-topology: 2
    Source: KSTREAM-SOURCE-0000000004 (topics: [KSTREAM-EXTERNAL-CALL-0000000005-response])
      --> KSTREAM-MAPVALUES-0000000006
    Processor: KSTREAM-MAPVALUES-0000000006 (stores: [])
      --> KSTREAM-SINK-0000000007
      <-- KSTREAM-SOURCE-0000000004
    Sink: KSTREAM-SINK-0000000007 (topic: output)
      <-- KSTREAM-MAPVALUES-0000000006
   Sub-topology: 1
    Source: KSTREAM-SOURCE-0000000002 (topics: [KSTREAM-EXTERNAL-CALL-0000000005-request])
      --> KSTREAM-EXTERNAL-CALL-0000000005
    Processor: KSTREAM-EXTERNAL-CALL-0000000005 (stores: [])
      --> KSTREAM-SINK-0000000003
      <-- KSTREAM-SOURCE-0000000002
    Sink: KSTREAM-SINK-0000000003 (topic: KSTREAM-EXTERNAL-CALL-0000000005-response)
      <-- KSTREAM-EXTERNAL-CALL-0000000005
   Sub-topology: 0
    Source: KSTREAM-SOURCE-0000000000 (topics: [input])
      --> KSTREAM-SINK-0000000001
    Sink: KSTREAM-SINK-0000000001 (topic: KSTREAM-EXTERNAL-CALL-0000000005-request)
      <-- KSTREAM-SOURCE-0000000000
```

![image](https://user-images.githubusercontent.com/3295357/171184423-1790e193-c903-4ff7-94d7-a0d802d233fa.png)

SubTopology 1 will be executed by a dedicated external stream thread with asynchronous pattern and retry policy.
Does not side effect with the other subtopology and the other stream threads.

Implementation WIP

**Comment by LGouellec** [comment]
Public API will :
```csharp
// call external system at middle of your topology
IKStream<K1, V1> ExternalCallAsync<K1, V1>(
            Func<ExternalRecord<K, V>, ExternalContext, Task<KeyValuePair<K1, V1>>> asyncExternalCall,
            RetryPolicy retryPolicy,
            RequestSerDes<K, V> requestSerDes = null,
            ResponseSerDes<K1, V1> responseSerDes = null,
            string named = null);

// call external system at the end of your topology
void ExternalCallAsync(
            Func<ExternalRecord<K, V>, ExternalContext, Task> asyncExternalCall,
            RetryPolicy retryPolicy,
            RequestSerDes<K, V> requestSerDes = null,
            string named = null);
```

**Comment by RogerSep** [comment]
I like the addition, but I wonder why not just add async variations, like `MapAsync`, `ForeachAsync`, `FlatmapAsync`, etc.
Does that retry policy come from something like Polly? It looks to me like that should be up to the user to do.

**Comment by RogerSep** [comment]
Another question is how it plays out with something like a scope to be able to resolve dependency injection.

**Comment by LGouellec** [comment]
Because Kafka Streams is the stream processing library for Apache Kafka and the aim is to process data from kafka topic to another kafka topic. And calling external system inside your topology can appears some error. 

First one is if your consumer doesn't fetch messages during `max.poll.interval.ms`(default value : 5 minutes), your consumer will die. 
You can easily add a bottleneck inside your topology with calling REST Api, make an insert in a oracle db etc ...

The best pattern is to write the record into another "sink" topic and use a `kafka-connect` connector to call Rest API, insert into an oracle db etc ..

Stream Thread Model :
- Fetch batch of messages  (0 and `max.poll.records`) (default value : 500)
- Process batch of messages (if you call an external system here and we have 1s latency, 500 s >= `max.poll.interval.ms eg 5 minutes`
- Flush & Commit message processed

But in reality, some developers use this DSL for calling external system (in JAVA but also in .NET). So this feature is just to allow the availability to call properly an external system. 
So if a developer will use `ExternalCallAsync`, this external processing will be executed by a dedicated thread with this model :

External Stream Thread model : 
- Consumer one message unitary
- Process the external lambda
  - if the task failed with a retryable exception : 
     - retry while number of retry is exceed
     - if startFirstProcessTime + timeout < DateTime.Now (so if the processing take a long time and near approach to max.poll.interval.ms), we stop the processing
  - if the retry policy is exceed (number of retry or not enough time to process), the strategy defined is call
    - SKIP : skip the message, consume and process the next message
    - FAIL : The external topology will dead
    - BUFFERED : the message is pushed into a local buffer. If the buffer is FULL (retry policy config : MaxBufferSize), because the external system is DEAD and all messages are coming into the local buffer, we paused all source partitions. And we will try to reduce the buffer size later.
- Flush & Commit messages

We can see that the thread modeling for external system is not the same that for joining two topics, just in memory `map(..)`, `foreach(..)`, `flatmap(...)` etc ... 
Because you have to paused consuming partitions if the external system is down, because you have to stop the processing if the `max.poll.interval.ms` will exceed soon. 
And the classic stream thread doesn't implement these features because you have an impact on your processing throughput. 
Using external stream thread to process only external calling request minimize the impact on the rest of your topology. But you can have a bottleneck if the system is really slow compared the kafka source topic throughput. In this case, you have to monitor the lag about the `-request` topic. 

I don't understand your second question. Sorry 🙁

**Comment by LGouellec** [comment]
- [ ] Unit test external stream thread
- [ ] Xml document in code
- [ ] Update metrics documentation
- [ ] Create a dedicated page about "How calling an external system ?"

**Comment by LGouellec** [comment]
New public API (hi @RogerSep 😃 )

``` csharp
        IKStream<K1, V1> MapAsync<K1, V1>(
            Func<ExternalRecord<K, V>, ExternalContext, Task<KeyValuePair<K1, V1>>> asyncMapper,
            RetryPolicy retryPolicy = null,
            RequestSerDes<K, V> requestSerDes = null,
            ResponseSerDes<K1, V1> responseSerDes = null,
            string named = null);
        
        IKStream<K1, V1> FlatMapAsync<K1, V1>(
            Func<ExternalRecord<K, V>, ExternalContext, Task<IEnumerable<KeyValuePair<K1, V1>>>> asyncMapper,
            RetryPolicy retryPolicy = null,
            RequestSerDes<K, V> requestSerDes = null,
            ResponseSerDes<K1, V1> responseSerDes = null,
            string named = null);
        
        IKStream<K, V1> MapValuesAsync<V1>(
            Func<ExternalRecord<K, V>, ExternalContext, Task<V1>> asyncMapper,
            RetryPolicy retryPolicy = null,
            RequestSerDes<K, V> requestSerDes = null,
            ResponseSerDes<K, V1> responseSerDes = null,
            string named = null);
        
        IKStream<K, V1> FlatMapValuesAsync<V1>(
            Func<ExternalRecord<K, V>, ExternalContext, Task<IEnumerable<V1>>> asyncMapper,
            RetryPolicy retryPolicy = null,
            RequestSerDes<K, V> requestSerDes = null,
            ResponseSerDes<K, V1> responseSerDes = null,
            string named = null);

        void ForeachAsync(
            Func<ExternalRecord<K, V>, ExternalContext, Task> asyncAction,
            RetryPolicy retryPolicy = null,
            RequestSerDes<K, V> requestSerDes = null,
            string named = null);
```

**Comment by RogerSep** [comment]
Awesome! why did you decide on the async variations?
If you point me where I can do it, I can help with 
> Create a dedicated page about "How calling an external system?"

**Comment by LGouellec** [comment]
@RogerSep,

Because after some reflexion internally, I think it makes more sense to have these ones compared with just an `ExternalCallAsync()`.

As well, developers could map/flatMap key/value or just value with an asynchronous processing (calling a database, HTTP Api, or so on ...).

It would be great ! 
For documentation, I had thought two things :
- Update the [stateless page](https://github.com/LGouellec/kafka-streams-dotnet/blob/develop/docs/stateless-processors.md) for adding MapAsync(), FlatMapAsync(), MapValuesAsync(), FlatMapValuesAsync() and ForeachAsync(). A brief describe for each new DSL method like the other examples.
- Add a dedicated webpage in two parts : How Streamiz do to make asynchronous processing ? (which pattern use, ...) and in second part more a tutoriel with a schema to illustrate the use case, a docker-compose stack, a topology implementation and some screenshots on "How make an asynchronous processing with Streamiz" and I had thought about a use case like : Stream topic A - MapValuesAsync(..) with a mongodb collection - Join an another stream B - Publish in topic C.

And later I will add the page regarding the threading model.

**Comment by LGouellec** [comment]
PR merged

**Comment by LGouellec** [comment]
Example use case :

```csharp
            StreamBuilder builder = new StreamBuilder();

            var client = new MongoClient(
                "mongodb://admin:admin@localhost:27017"
            );
            var database = client.GetDatabase("streamiz");

            builder
                .Stream<string, string>("person")
                .MapValuesAsync(async (record, _) => {
                    var persons = await database
                        .GetCollection<Person>("adress")
                        .FindAsync((p) => p.name.Equals(record.Key))
                        .Result.ToListAsync();
                    return persons.FirstOrDefault()?.address.city;
                },
                    RetryPolicy
                        .NewBuilder()
                        .NumberOfRetry(10)
                        .RetryBackOffMs(100)
                        .RetriableException<Exception>()
                        .RetryBehavior(EndRetryBehavior.BUFFERED)
                        .Build())
                .To("person-city");
```
