### ISSUE TITLE
Migrate all CI/CD to Github actions

### ISSUE THREAD

**Issue by LGouellec** [LGouellec/kafka-streams-dotnet#15]
Migrate all CI/CD to Github actions

=> Remove Circle CI
=> Sonar Analysis in Github actions

**Comment by joaovitorpina** [comment]
Hey @LGouellec do you need help implementing this task? I can do it, if you need it.

**Comment by LGouellec** [comment]
Hi @joaovitorpina ,

As you want, the aim of this issue is to use only GitHub actions for ci/cd, integration and release jobs.

Feel free to make a PR.

Appreciate thanks
