### ISSUE TITLE
Persistent RockDB store cause error on Linux OS

### ISSUE THREAD

**Issue by DenisXKR** [LGouellec/kafka-streams-dotnet#159]
After upgrading to the latest version (Streamz: 1.3.0) Persistent RockDB stopped working. All topology tests pass and locally on windows service works fine but when I deploy it to microk8s it fails.

Code sample
```
var streamBuilder = new StreamBuilder();
 streamBuilder.Stream<string, string>("Commands")
    .ToTable(Materialized<string, string, IKeyValueStore<string, string>>.Create(Stores.PersistentKeyValueStore("State")));

```
Config
```
StreamConfig = new StreamConfig<StringSerDes, StringSerDes>
 {
                ApplicationId = this.GetType().Assembly.GetName().Name,
                BootstrapServers = BrokerBootstrapServers,
                AutoOffsetReset = AutoOffsetReset.Earliest,
                SchemaRegistryUrl = DatabaseSchemaUrl,
                SchemaRegistryRequestTimeoutMs = 5000,
                RequestTimeoutMs = 5000,
                SocketTimeoutMs = 5000,
                AllowAutoCreateTopics = true,
                StateDir = $"."
 };
```

Log: 
info: Streamiz.Kafka.Net.Processors.StreamThread[0]
      stream-thread[Service.kafka-58d1bc16-42b5-44f8-bb0c-f2d53f162dc7-stream-thread-0] Creating shared producer client
info: Streamiz.Kafka.Net.Processors.StreamThread[0]
      stream-thread[Service.kafka-58d1bc16-42b5-44f8-bb0c-f2d53f162dc7-stream-thread-0] Creating consumer client
info: Streamiz.Kafka.Net.KafkaStream[0]
      stream-application[Service.Kafka] State transition from CREATED to REBALANCING
info: Streamiz.Kafka.Net.KafkaStream[0]
      stream-application[Service.Kafka] Starting Streams client with this topology : Topologies:
         Sub-topology: 0
          Source: KSTREAM-SOURCE-0000000000 (topics: [Commands])
            --> KSTREAM-TOTABLE-0000000001
          Processor: KSTREAM-TOTABLE-0000000001 (stores: [State])
            --> none
            <-- KSTREAM-SOURCE-0000000000
      
info: Streamiz.Kafka.Net.Processors.StreamThread[0]
      stream-thread[Service.kafka-58d1bc16-42b5-44f8-bb0c-f2d53f162dc7-stream-thread-0] Starting
info: Streamiz.Kafka.Net.Processors.StreamThread[0]
      stream-thread[Service.kafka-58d1bc16-42b5-44f8-bb0c-f2d53f162dc7-stream-thread-0] State transition from CREATED to STARTING
Unhandled exception. Confluent.Kafka.KafkaException: Local: Erroneous state
   at Confluent.Kafka.Impl.SafeKafkaHandle.AssignImpl(IEnumerable`1 partitions, Func`3 assignMethodErr, Func`3 assignMethodError)
   at Confluent.Kafka.Impl.SafeKafkaHandle.Assign(IEnumerable`1 partitions)
   at Confluent.Kafka.Consumer`2.Unassign()
   at Confluent.Kafka.Consumer`2.RebalanceCallback(IntPtr rk, ErrorCode err, IntPtr partitionsPtr, IntPtr opaque)

Versions: 
  .Net 6.0
  Confluent.Kafka: 1.9.0
  Streamz: 1.3.0
  OS: 6.0-alpine
  Kafka: 6.2.0-ccs (Commit:1a5755cf9401c84f)

Checklist
=========

Please provide the following information:
 - [ x ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ x ] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [ x ] Streamiz.Kafka.Net nuget version.
 - [ x ] Apache Kafka version.
 - [ x  ] Client configuration.
 - [ x ] Operating system.
 - [ x ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
Hi @DenisXKR, 

First I think, It would be nice if I added the details of the exception. Because the exception here is during the partition assignment process, but we don't have the origin. Probably it's due to init the rocks db store. So I will add PR to log with more information exception during assignment. 

Second, do you have install all rocksdb dependencies ? For instance, my github CI works on ubuntu and I had some dependencies before building and running a streamiz app.
https://github.com/LGouellec/kafka-streams-dotnet/blob/0fcd65dedc2f294edd4791c5523b022bfaa8adae/.github/workflows/build-ci.yml#L29

**Comment by DenisXKR** [comment]
It looks like the issuer is in dependences but, it's not able to load libbz2.so.1.0 despite it is installed. 

Error loading shared library **libbz2.so.1.0**: No such file or directory (needed by /app/librocksdb.so)\nlibrocksdb-7.2.2.so: (NativeLoadException) dlopen: Error loading shared library librocksdb-7.2.2.so: No such file or directory\nlibrocksdb-7.2.so: (NativeLoadException) dlopen: Error loading shared library librocksdb-7.2.so: No such file or directory\nlibrocksdb-7.so: (NativeLoadException) dlopen: Error loading shared library librocksdb-7.so: No such file or directory\nlibrocksdb.so: (NativeLoadException) dlopen: Error loading shared library librocksdb.so: No such file or directory\n   at NativeImport.Importers.Import[T](INativeLibImporter importer, String libName, String version, Boolean suppressUnload)\n   at NativeImport.Auto.Import[T](String name, String version, Boolean suppressUnload)\n   at RocksDbSharp.Native..cctor()\n   --- End of inner exception stack trace ---\n   at RocksDbSharp.OptionsHandle..ctor()\n   at RocksDbSharp.ColumnFamilyOptions..ctor()\n   at RocksDbSharp.DbOptions..ctor()

/usr/lib # ls -l
total 12272
drwxr-xr-x    3 root     root          4096 Jul 12 15:28 cmake
drwxr-xr-x    2 root     root          4096 May 23 16:51 engines-1.1
drwxr-xr-x    3 root     root          4096 Jul  6 15:29 krb5
lrwxrwxrwx    1 root     root         15 Jul 12 15:28 **libbz2.so -> libbz2.so.1.0.8**
lrwxrwxrwx    1 root     root         15 Jul 12 15:28 **libbz2.so.1 -> libbz2.so.1.0.8**
-rwxr-xr-x    1 root     root         58128 Apr  5  2020 **libbz2.so.1.0.8**

Perhaps there is a mismatch in naming **libbz2.so.1.0** and **libbz2.so.1**

**Comment by DenisXKR** [comment]
It was only the top of the Iceberg :)
Since Apline is very truncated there are a lot of other skipped dependencies, therefore using librocksdb.so from the build is almost not possible (You need to install a lot of packages and symbols). 

I used Alpain rocksdb pack and substitute it with a symbolic link.

Docker file:
```
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine AS publish
RUN apk add rocksdb
WORKDIR /app
COPY --from=build /app/publish .
RUN rm librocksdb.so
RUN ln -s /usr/lib/librocksdb.so.7 /app/librocksdb.so
```
