### ISSUE TITLE
GroupBy does not use KeySerde from IKStream

### ISSUE THREAD

**Issue by lollo25** [LGouellec/kafka-streams-dotnet#164]
Hi @LGouellec ,
as you can see here 
https://github.com/LGouellec/kafka-streams-dotnet/blob/d03bbfc819aba7801cdff085d19e9d49ebfcca48/core/Stream/Internal/KStream.cs#L425-L426
the function does not provide to `Grouped<KR, V>.Create` the `KeySerdes` but only the `ValueSerdes` making this overload quite unuseful in all the cases where the key serde is not the default one.

Moreover, I will add an overload that allows to pass the serdes as parameters, as it happens for other methods like `To` or `Stream`.

Thanks
Lorenzo

**Comment by LGouellec** [comment]
Hi @lollo25, 

You can use `GroupBy` method with key serdes as a template : 

```csharp
builder.Stream<string, string>("topic")
                .GroupBy<int, Int32SerDes>((k, v) => v.Length)
                .Count();
```

**Comment by lollo25** [comment]
Yes, correct but I cannot use an existing instance of the serde. Don't you think it is worth adding this feature?

**Comment by LGouellec** [comment]
Yes it's planned for 1.4

**Comment by lollo25** [comment]
Ok, great! Thanks @LGouellec ! I am gonna close this issue.

**Comment by njlr** [comment]
Did this make it into a release? 

I cannot see an overload for `GroupBy` that takes an `ISerDes` value or an `Grouped<KR, V>`:

https://github.com/LGouellec/streamiz/blob/3067fa5e70e9827c81b0a1e6b7fc78d1c2e7638c/core/Stream/Internal/KStream.cs#L635-L685
