### ISSUE TITLE
Providing custom class as a DefaultValueSerDes giving an error

### ISSUE THREAD

**Issue by Shikha4599** [LGouellec/kafka-streams-dotnet#177]
Description
We have made our consumer class where we are consuming messages from Kafka producer. We wanted to customize our Kafka stream by providing customized class in DefaultValueSerDes, which is not working and giving me error.

**THIS IS MY PROGRAM.CS FILE**
`     // Stream configuration
        var config = new StreamConfig();

        config.ApplicationId = "app-testing";
        config.BootstrapServers = "localhost:9092";
        config.DefaultKeySerDes = new StringSerDes();
        config.DefaultValueSerDes = new ABC();

        StreamBuilder builder = new StreamBuilder();

        IKStream<string, ABC> str = builder.Stream<string, ABC>("test-input");
        str.Filter((k, v) => v.Data >= 25 && v.Data <= 50).To("test-output");

        Topology t = builder.Build();

        // Create a stream instance with topology and configuration
        KafkaStream stream = new KafkaStream(t, config);

        // Subscribe CTRL + C to quit stream application
        Console.CancelKeyPress += (o, e) =>
        {
            stream.Dispose();
        };

        // Start stream instance with cancellable token
        await stream.StartAsync();  `

**THIS IS MY PROVIDED JSON TYPE IN KAFKA PRODUCER**
{"Name": "DND", "Data": 37}

**THIS IS MY CUSTOMIZED CLASS ABC.CS**
`
public class ABC : ISerDes
    {
        public string Name { get; set; }
        public int Data { get; set; }

        public object DeserializeObject(byte[] data, SerializationContext context)
        {
            var bytesAsString = Encoding.UTF8.GetString(data);
            return JsonConvert.DeserializeObject<ABC>(bytesAsString);
        }

        public void Initialize(SerDesContext context)
        {
            context.Config.BootstrapServers = "localhost:9092";
            context.Config.ApplicationId = "app-testing";
        }

        public byte[] SerializeObject(object data, SerializationContext context)
        {
            var a = JsonConvert.SerializeObject(data);
            return Encoding.UTF8.GetBytes(a);
        }
    }`

**THIS IS THE ERROR WE ARE RECEIVING**
<img width="985" alt="kafka" src="https://user-images.githubusercontent.com/114483875/192510841-629c2807-d7b1-4637-a49b-1f24c3de6af6.png">

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [ ] Streamiz.Kafka.Net nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
Hi @Shikha4599,

Thanks for your issue.

Could you please test this implementation for `ABC.cs` :
```csharp
    public class ABC : AbstractSerDes<ABC>
    {
        public string Name { get; set; }
        public int Data { get; set; }
        
        public override ABC Deserialize(byte[] data, SerializationContext context)
        {
            var bytesAsString = Encoding.UTF8.GetString(data);
            return JsonConvert.DeserializeObject<ABC>(bytesAsString);
        }

        public override byte[] Serialize(ABC data, SerializationContext context)
        {
            var a = JsonConvert.SerializeObject(data);
            return Encoding.UTF8.GetBytes(a);
        }
    }
```

**Comment by OneCricketeer** [comment]
FWIW, `Data` field should be named `Value` according to the JSON shown

**Comment by LGouellec** [comment]
> 

By the way, it's not a good practice to use the same class for the BEAN and the SerDes. 
I recommend you to split into two different classes.

**Comment by Shikha4599** [comment]
> Hi @Shikha4599,
> 
> Thanks for your issue.
> 
> Could you please test this implementation for `ABC.cs` :
> 
> ```cs
>     public class ABC : AbstractSerDes<ABC>
>     {
>         public string Name { get; set; }
>         public int Data { get; set; }
>         
>         public override ABC Deserialize(byte[] data, SerializationContext context)
>         {
>             var bytesAsString = Encoding.UTF8.GetString(data);
>             return JsonConvert.DeserializeObject<ABC>(bytesAsString);
>         }
> 
>         public override byte[] Serialize(ABC data, SerializationContext context)
>         {
>             var a = JsonConvert.SerializeObject(data);
>             return Encoding.UTF8.GetBytes(a);
>         }
>     }
> ```

Thankyou @LGouellec for the above solution.
After implementing the above code in ABC.cs, it is throwing me new exception.

<img width="717" alt="kafka1" src="https://user-images.githubusercontent.com/114483875/192709852-cc22daf5-7d6b-4962-9c3c-63783b50aa00.png">
<img width="889" alt="kafka2" src="https://user-images.githubusercontent.com/114483875/192709874-21830795-fd25-4054-af5b-668b481253fb.png">

**Comment by LGouellec** [comment]
@Shikha4599, 

Looks like your value in the source kafka topic is null. If not, maybe you have to add a breakpoint into the ABC serdes in the `Deserialize(..)`method to observe the behavior during the deserialiazation ?

**Comment by Shikha4599** [comment]
> @Shikha4599,
> 
> Looks like your value in the source kafka topic is null. If not, maybe you have to add a breakpoint into the ABC serdes in the `Deserialize(..)`method to observe the behavior during the deserialiazation ?

I am sending this data from the kafka producer

<img width="608" alt="kafka3" src="https://user-images.githubusercontent.com/114483875/192714887-402e0880-7b4e-4393-af8f-2da74063e04a.png">

But when I am putting breakpoint on Deserialize method of ABC.cs, I am receiving null data
<img width="673" alt="kafka4" src="https://user-images.githubusercontent.com/114483875/192715088-30f68607-3113-4e66-9024-6c1cfef5ea78.png">

**Comment by Shikha4599** [comment]
> Hi @Shikha4599,
> 
> Thanks for your issue.
> 
> Could you please test this implementation for `ABC.cs` :
> 
> ```cs
>     public class ABC : AbstractSerDes<ABC>
>     {
>         public string Name { get; set; }
>         public int Data { get; set; }
>         
>         public override ABC Deserialize(byte[] data, SerializationContext context)
>         {
>             var bytesAsString = Encoding.UTF8.GetString(data);
>             return JsonConvert.DeserializeObject<ABC>(bytesAsString);
>         }
> 
>         public override byte[] Serialize(ABC data, SerializationContext context)
>         {
>             var a = JsonConvert.SerializeObject(data);
>             return Encoding.UTF8.GetBytes(a);
>         }
>     }
> ```

This worked. Thankyou so much for the response @LGouellec

**Comment by LGouellec** [comment]
@Shikha4599 

Perfect ! So I close this issue. If you have another question/issue, please open a new one.
