### ISSUE TITLE
CompositeReadonlyKeyValueStore throws NullReferenceException if key does not exist in one of the stores

### ISSUE THREAD

**Issue by MAOliver** [LGouellec/kafka-streams-dotnet#180]
Description
===========

Line 83 in CompositeReadOnlyKeyValueStore.cs is this:
```csharp
                return stores.FirstOrDefault(x => x.Get(key) != null).Get(key);
```

This throws a NullReferenceException in the case where there is no store with the given key.

Changing this line to something like this would correct the issue without running afoul of the type system null-checking (there may be a more elegant solution, but, this would work).

```csharp
                return stores.Where(x => x.Get(key) != null).Select(x=> x.Get(key)).FirstOrDefault();
```

How to reproduce
================

Search a KeyValueStore for a key that does not exist.

**Comment by LGouellec** [comment]
Hi @MAOliver,

Thanks for your issue. I checked this one and added this issue to the 1.4.0 milestone.

Best regards
