### ISSUE TITLE
PersistentWindowStore lazy loading issue

### ISSUE THREAD

**Issue by ognenbek** [LGouellec/kafka-streams-dotnet#193]
Description
===========
Hey @LGouellec, I am currently working with stremiz on the `IKStream-IKStream` Join approach with `PersistentWindowStore`. While everything is working as expected on the first run of the application, I noticed an issue when restarting the app. The segments in the Stores are lazy loaded, meaning that they will be loaded as soon as the first message comes in the stream.

It seems like the `RocksDbKeyValue` segments are not created on initialization but on the first put in the db.

**The issue that can occur from the lazy fetching is the following:**

- We have two topics, topic1 and topic2 which are joined.
- topics are filled with messages and at some point of time, we receive message on the first topic1: keyN : ValueN and the streams application is restarted before the other message with the same key is sent to the second topic topic2
- Streams application is restarted
- After restarting the segments in the Stores are lazy loaded, so if the keyN message comes to the second topic (keyN : ValueN), before at least one message comes in the first topic1, then the message would not be joined because the topic1 segment is not loaded and thus all of the messages inside of it.
- In the end the messages which were not joined before the restart wouldn't be joined after the restart.

How to reproduce
================
1. Create IKStream-IKStream PersistentWindowStore Join application.
2.  Send message to the first topic
3. Restart the application
4. Send message with same key to the secondtopic
5. The messages would not be joined

**stremiz version: 1.3.2 and 1.4.0-rc1**

**Comment by LGouellec** [comment]
Merged into the 1.4.
1.4.0 release soon. Stay tuned
