### ISSUE TITLE
Question: How to overwrite prefix of internal topics (application id fails)

### ISSUE THREAD

**Issue by DatStorm** [LGouellec/kafka-streams-dotnet#253]
Hey.

First of thanks for a lot of great work!

Description
===========
We have a problem with our internal topics they do not seem to follow the pattern described here:
https://docs.confluent.io/platform/current/streams/developer-guide/manage-topics.html
![image](https://user-images.githubusercontent.com/23613201/236811277-f84567e6-76b5-49ad-b60e-f746aae0b853.png)

We are using Confluent cloud and to ensure no clashes between topics we have created an application id prefix that should be applied to all internal topics but this does not seem to be the case.

How to reproduce
================

1. Start the example application
2. Look at the initializing logs and see that internal stream topics are not prefixed with application id but with `KSTREAM-MAPVALUES-ASYNC-0000000008-request`

![image](https://user-images.githubusercontent.com/23613201/236812209-27dc93d4-44bd-48f8-bbe2-e4fd6ea11b95.png)

Checklist
=========

More info can be provided if needed. 

Please provide the following information:
 - [X ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [ ] Streamiz.Kafka.Net nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
Hi @DatStorm, 

Can you share your topology please ? 

Best regards,

**Comment by LGouellec** [comment]
@DatStorm , 

I tried with this topology and the internal `request` and `response` topics are correctly prefixed with the `application.id` 
<img width="735" alt="image" src="https://github.com/LGouellec/kafka-streams-dotnet/assets/3295357/0d28417e-49f8-40c2-973f-f7b6e26702ab">

``` csharp
      var config = new StreamConfig<StringSerDes, StringSerDes>();
            config.ApplicationId = "test-app";
            config.BootstrapServers = "localhost:9092";
           
            StreamBuilder builder = new StreamBuilder();
            
            builder.Stream<string, string>("inputs")
                .Peek((k, v) => logger.LogInformation("key={k} value={v}", k,v))
                .MapValuesAsync(async (record, _) => await Task.FromResult(record.Value.ToUpper()))
                .To("output");
            
            Topology t = builder.Build();
            KafkaStream stream1 = new KafkaStream(t, config);
            
            Console.CancelKeyPress += (_, _) => stream1.Dispose();
            
            await stream1.StartAsync();
```

**Comment by DatStorm** [comment]
I just ran it locally and you are right the topics created are in fact prefixed with the application id but the topology printed in the log (in the beginning) does not have them and that is a bit confusing.


![image](https://github.com/LGouellec/kafka-streams-dotnet/assets/23613201/21799248-acac-4024-9de2-a91e1f04e48e)

**Comment by LGouellec** [comment]
The topology printed at the beginning is agnostic to the application id.  Same for the others internal topics (changelog and repartition).

**Comment by DatStorm** [comment]
I was not aware. So for the misunderstanding.

The issue can be closed.
