### ISSUE TITLE
Getting involved

### ISSUE THREAD

**Issue by sachabarber** [LGouellec/kafka-streams-dotnet#26]
I would like to get involved with this what is the best way to connect?

**Comment by sachabarber** [comment]
Be good to know how you started the port, by looking at existing scala/java code etc etc

Perhaps an initial meeting would be good

**Comment by LGouellec** [comment]
Hi, very happy to read you. I will send a mail with information ASAP :)

**Comment by LGouellec** [comment]
Email sent !
