### ISSUE TITLE
gitpod doesn't work properly

### ISSUE THREAD

**Issue by inwenis** [LGouellec/kafka-streams-dotnet#272]
Description
===========

I tried gitpod, endedup with this:
```
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Closing
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Suspended created
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Task 0-0 state transition from CREATED to SUSPENDED
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Task 0-0 state transition from SUSPENDED to CLOSED
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Closed
info: Streamiz.Kafka.Net.Kafka.Internal.StreamsRebalanceListener[0]
      Partition revocation took 00:00:00.0011460 ms
        Current suspended active tasks: input-[0],input-[1],input-[2],input-[3],sample-streamiz-demo-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition-[0],sample-streamiz-demo-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition-[1],sample-streamiz-demo-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition-[2],sample-streamiz-demo-KSTREAM-AGGREGATE-STATE-STORE-0000000004-repartition-[3]
      
info: Streamiz.Kafka.Net.Processors.StreamThread[0]
      stream-thread[sample-streamiz-demo-5b825ee4-9941-4c41-b2ec-101b9f900340-stream-thread-0] Shutdown complete
info: Streamiz.Kafka.Net.Processors.StreamThread[0]
      stream-thread[sample-streamiz-demo-5b825ee4-9941-4c41-b2ec-101b9f900340-stream-thread-0] State transition from PENDING_SHUTDOWN to DEAD
info: Streamiz.Kafka.Net.KafkaStream[0]
      stream-application[sample-streamiz-demo] State transition from REBALANCING to ERROR
fail: Streamiz.Kafka.Net.Processors.StreamStateManager[0]
      All stream threads have died. The instance will be in error state and should be closed
gitpod /workspace/kafka-streams-dotnet (develop) $ 
```

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [ ] Streamiz.Kafka.Net nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
Hi @inwenis,

Thanks for your issue. I will check beginning of next week. 

By the way, can you put the complete logs please ?

**Comment by inwenis** [comment]
[output.log](https://github.com/LGouellec/kafka-streams-dotnet/files/12050020/output.log)
Attaching all the logs I could copy from the bash terminal

**Comment by LGouellec** [comment]
@inwenis , 

After a rapid analysis, the gitpod container miss a dependency (`rocksdb`). 

So open a workspace, the streamiz application will fail, don't worry. 
Run this command :
``` bash
sudo apt-get install librocksdb-dev
```
And restart the streamiz application, normally it works. 

I will update my `develop` branch next week.

**Comment by LGouellec** [comment]
fixed
