### ISSUE TITLE
Unable to process messages when using MapValuesAsync

### ISSUE THREAD

**Issue by Numatic-Hector** [LGouellec/kafka-streams-dotnet#280]
Description
===========

Unable to process messages when using `MapValuesAsync`.

How to reproduce
================

StreamProcessor:
```cs
StreamBuilder builder = new();
builder.Stream<string, EventWrapper>(_appSettings.KafkaSourceTopic, new StringSerDes(), new SchemaAvroSerDes<EventWrapper>())
   .MapValuesAsync(async (message, _) => await _eventMapper.Apply(message.Value))
   .Peek((key, value) => _log.Info($"Processed message {key}"))
   .To(_appSettings.KafkaDestinationTopic, new StringSerDes(), new StringSerDes());

return builder.Build();
```

EventMapper:
```cs
public async Task<string> Apply(EventWrapper value)
{
    return await Task.FromResult("test");
}
```

No messages are processed, and no errors are logged.

**Comment by attributeerror** [comment]
For context, we've also tried setting the `requestSerDes` & `responseSerDes` parameters in the `MapValuesAsync` method to `new RequestSerDes<string, EventWrapper>(new StringSerDes(), new SchemaAvroSerDes<EventWrapper>())` & `new ResponseSerDes<string, string>(new StringSerDes(), new StringSerDes())` respectively.

It looks to me as though there's a problem in producing the initial message to the internal `request` topic as no messages are produced there, but the stream processor seems to get stuck when shutting down which tells me that it's busy processing _something_.

Is this how we should be handling producing Avro models to internal topics or is there a different way?

**Comment by LGouellec** [comment]
Hi @attributeerror  and @Numatic-Hector , 

Yes this is how you have to handle with Avro model. 
Can you enable Debug logging first and post your logs in this issue please ? 

```csharp
var config = new StreamConfig<StringSerDes, StringSerDes>
            {
                ApplicationId = $"test-app",
                BootstrapServers = "localhost:9092",
                AutoOffsetReset = AutoOffsetReset.Earliest,
                Logger = LoggerFactory.Create(b =>
                {
                    b.SetMinimumLevel(LogLevel.Debug);
                    b.AddConsole();
                }),
                Debug = "all"
            };
```

**Comment by attributeerror** [comment]
Hi @LGouellec - certainly, I've uploaded the logs to Google Drive:
https://drive.google.com/file/d/15gvSclDykkCAXhVHjzTbkA7RX_WnZ3tB/view?usp=sharing

**Comment by LGouellec** [comment]
I don't see nothing special, can you start your application, publish some incoming records into the `Oracle.EBS.Shipping.Events` topic and attach the logs please ?

**Comment by attributeerror** [comment]
@LGouellec Certainly, uploaded to Google Drive again.
https://drive.google.com/file/d/1bintTWd0tNUDkrU9GJwOY1UgKIvK-uAg/view?usp=drive_link
Can you request access to the file please?^

I noticed this whilst all of the other messages were running past, could this be something to do with it?:  
```
dbug: Streamiz.Kafka.Net.Kafka.Internal.KafkaLoggerAdapter[0]
      Log producer oracle-shipping-event-stream-processor-55321a20-53fc-419a-afcf-b3f374735aa2-stream-thread-0-streamiz-producer#producer-2 - [thrd:10.0.44.152:30768/2]: 10.0.44.152:30768/2: oracle-shipping-event-stream-processor-KSTREAM-MAPVALUES-ASYNC-0000000005-request [0]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) encountered error: Broker: Not enough in-sync replicas (actions Retry,MsgNotPersisted)
```

**Comment by LGouellec** [comment]
@attributeerror, 

Yes exactly, it means the producer can't produce into the request topic because the number of in-sync replica is not enought to satisfy the acks=all. 
So probably you have one or multiple broker fails, or very slow and these brokers are ejected from the ISR list.

So to resume, if the producer can't produce into the request topic, it's normal that no messages are process into the MapValuesAsync. 

Best regards,

**Comment by attributeerror** [comment]
@LGouellec 

Makes sense. Only problem I have is that the topic it is referencing was created as part of the MapValuesAsync topology step. How can I ensure that the topic is configured properly going forward? Could this be another issue specific to Strimzi..?

Thanks!

**Comment by LGouellec** [comment]
@attributeerror, 

All internals topics are created with the same number of partitions than the source topic (in your case : `Oracle.EBS.Shipping.Events`) and the replication factor used is `streamConfig.ReplicationFactor` which by default is equal to 1. 

And by default, the producer acks is configured to `all`.

Maybe you can list the details of the internal request topics, and see the the ISR list for each partition, and detect potential partitions under min isr. This kind of metrics is also exposed at the broker level.

**Comment by attributeerror** [comment]
@LGouellec Thanks for bringing the `streamConfig.ReplicationFactor` option to my attention. I hadn't noticed it before, but it's exactly what I needed. We have our cluster configured to set all topics to be created with a `min.insync.replicas` of 2 - which would be why we were seeing the above error. I have changed this option to default to 3 replicas and it seems to be working fine now.

Thanks for your help as always!
