### ISSUE TITLE
Can't instantiate a new instance of StreamTableJoinProps<>

### ISSUE THREAD

**Issue by kevin-mcmanus** [LGouellec/kafka-streams-dotnet#285]
Description
===========

I'm trying to create a left join but get the following exception at runtime:

```
Streamiz.Kafka.Net.Errors.StreamsException: The inner serdes is not compatible to the actual value type XXXX. Provide correct Serdes via method parameters(using the DSL)
```

There's an overload to `.LeftJoin()` that takes in a `StreamTableJoinProps<>`, yet I can't find a way to create the object.  The constructor is marked as `internal`.  It looks like the tests pass due to an `InternalsVisibleTo()` attribute.

Ref: #240 

Unless I've missed something, please can we make the constructor public, or provide another mechanism to create the object.

I'm currently on the latest NuGet packages.

**Comment by LGouellec** [comment]
@kevin-mcmanus, 

It's a forget from my side. I will make the constructor public and publish a new release soon.

**Comment by kevin-mcmanus** [comment]
Thank you, much appreciated.
