### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by E4M9i** [LGouellec/kafka-streams-dotnet#29]
Hi there,
I know you're still in early days but do you perhaps have any perspective f performance?
I meant any benchmarking with basic functions built so far?
Or any rough comparison with KSqlDB?
Thanks
Ehsan

**Comment by LGouellec** [comment]
Hi,

Benchmarking with Java implementation is studying.
I would do it when I finished all the processor (stateless + statefull) and persistent state store (rocksDb impl, for moment I juste have an in memory store).

Regards,
