### ISSUE TITLE
How to serialize an Object using Avro Serializer where it is registered in the Schema Registry?

### ISSUE THREAD

**Issue by Marc19** [LGouellec/kafka-streams-dotnet#30]

**Comment by LGouellec** [comment]
Hi @Marc19, for moment Avro SerDes which interact with Schema Registry is not available.

**Comment by Marc19** [comment]
Hi @LGouellec, thanks man. Looking forward to it!

**Comment by LGouellec** [comment]
You have a workaround : 
- Sample stream application with avro + registry [here](https://github.com/LGouellec/kafka-streams-dotnet/tree/master/samples/sample-stream-registry]. Please read my ReadMe
- Sample producer to mocking data [here](https://github.com/LGouellec/kafka-streams-dotnet/tree/master/test/Producer-Avro)

Do not hesitate, if you have any questions

++

**Comment by Marc19** [comment]
I think I don't have access for the sample stream repo.

**Comment by LGouellec** [comment]
Retry, I made mistake in my comment

**Comment by Marc19** [comment]
Thank you, I really appreciate your effort!

I'm not sure but I think my current problem is, that my object is auto registered in the schema registry when it is first produced in a Kafka topic. So, I would prefer not to define the schema manually like you did in the Person object. 

So is there something I can do to achieve this?

**Comment by LGouellec** [comment]
With both modifications, it should be OK for your use case :)
- https://github.com/LGouellec/kafka-streams-dotnet/blob/a6f22cb047c04225ad2a771fa2c623031e0d6ee1/samples/sample-stream-registry/PersonSerDes.cs#L22
- https://github.com/LGouellec/kafka-streams-dotnet/blob/a6f22cb047c04225ad2a771fa2c623031e0d6ee1/test/Producer-Avro/Program.cs#L30

**Comment by LGouellec** [comment]
Streamiz packages was released in 1.0.0 version. 
A new nuget packages with name : Streamiz.Kafka.Net.SchemaRegistry.SerDes.Avro was release too. It contains avro serdes which interact with Schema Registry.

Don't hesitate to test !!
So I close this issue 😃
