### ISSUE TITLE
Provide a way to specify a custom partitioner

### ISSUE THREAD

**Issue by gurry** [LGouellec/kafka-streams-dotnet#310]
Please allow a custom partitioner to be set in Streamiz as we can do in Confluent.Kafka's ProducerBuilder?

My requirement is that when my topology emits events it needs to use a partition key that is different from the event key

**Comment by LGouellec** [comment]
@gurry 

What do you need as the inputs of the partitioner ? 
topic, key, value is enough ?

**Comment by gurry** [comment]
Thanks @LGouellec for picking this up.

Yes, absolutely. Topic, key and value would be perfect.
