### ISSUE TITLE
Error using producer message

### ISSUE THREAD

**Issue by ncupertino** [LGouellec/kafka-streams-dotnet#326]
Description
===========

I have a very strange error. On the server, it is unable to produce a filtered message

How to reproduce
================

My Code 

          _builder.Stream<string, string>(topicFrom)
                        .Filter((key, value) => ProcessFilterFunctionWithHeaders(processFunction, headers, value))
                        .To(topicTo);

Error:

Streamiz.Kafka.Net.Kafka.Internal.KafkaLoggerAdapter[0]
stream-thread[.NET Long Running Task] Error producer worker.fontepagadora-6d04e6d8-e651-4c0c-a5e5-2155becab784-stream-thread-0-streamiz-producer#producer-2 - sasl_ssl://internal--.sa-east-1.elb.amazonaws.com:9099/1: Disconnected (after 59957ms in state UP, 1 identical error(s) suppressed)
fail: Streamiz.Kafka.Net.Kafka.Internal.KafkaLoggerAdapter[0]
stream-thread[.NET Long Running Task] Error producer worker.fontepagadora--e651-4c0c-a5e5--stream-thread-0-streamiz-producer#producer-2 - 3/3 brokers are down
fail: Streamiz.Kafka.Net.Kafka.Internal.KafkaLoggerAdapter[0]
stream-thread[.NET Long Running Task] Error adƒmin worker.fontepagadora--e651--a5e5--streamiz-admin#producer-1 - sasl_ssl://internal--1821819867.sa-east-1.elb.amazonaws.com:9099/2: Disconnected (after 59626ms in state UP, 1 identical error(s) suppressed)
fail: Streamiz.Kafka.Net.Kafka.Internal.KafkaLoggerAdapter[0]
stream-thread[.NET Long Running Task] Error admin worker.fontepagadora-6d04e6d8-e651-4c0c-a5e5-2155becab784-streamiz-admin#producer-1 - 3/3 brokers are down

I suppress the brokers dns

**Comment by LGouellec** [comment]
Hey @ncupertino , 

Is it happens every time ? Looks your broker are down .. 
What is your configuration ? Are you sure that your cluster is healthy ?

**Comment by ncupertino** [comment]
Hi @LGouellec ,

Yes, is healthy. Other applications using dll Confluent.Kafka it's working. 

My configuration

 return new StreamConfig<StringSerDes, StringSerDes>
            {
                ApplicationId = _KafkaParameter.Consumidor.GroupId,
                BootstrapServers = _KafkaParameter.BootstrapServers,
                CommitIntervalMs = _KafkaParameter.Consumidor.ConsumerProccessMaxMS,
                SslCaLocation = string.IsNullOrEmpty(_KafkaParameter.Seguranca.CaminhoCertificado) ? @"/app/ca.crt" : _KafkaParameter.Seguranca.CaminhoCertificado,
                AutoOffsetReset = _KafkaParameter.Consumidor.AutoOffsetResetEarliest ? AutoOffsetReset.Earliest : AutoOffsetReset.Latest,
                SaslMechanism = SaslMechanism.ScramSha512,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslUsername = _KafkaParameter.Seguranca.ClientIdRhsso,
                SaslPassword = _KafkaParameter.Seguranca.ClientSecretRhsso,
                MetricsRecording = Streamiz.Kafka.Net.Metrics.MetricsRecordingLevel.INFO,
                FollowMetadata = true
            };

**Comment by LGouellec** [comment]
This periodically or every time when messages come in

**Comment by ncupertino** [comment]
Every time .

Explain better our scenario.

We have 10 partitions and 10 pods OpenShift. Our Kafka is from RedHat - AMQ Streams. 

Could this happen due to some broker timeout configuration?

**Comment by ncupertino** [comment]
In time...

There was a bug in the EOF Confluent dll that was fixed in version 2.3. The version we use of your dll is version 1.5. Is the released version 1.5.1 the most current version of Confluent Kafka?

**Comment by ncupertino** [comment]
https://github.com/confluentinc/confluent-kafka-dotnet/issues/2016

There was this error open in Confluent Kafka 2.2. I noticed that your DLL in version 1.5.1 still has the buggy version. Can you release version 1.5.2 by updating confluent to version 2.3?

**Comment by LGouellec** [comment]
I released a pre-release 1.6 version, can you try it ?

**Comment by ncupertino** [comment]
Is this version, being RC, reliable for production systems?

**Comment by LGouellec** [comment]
@ncupertino yes you can, I'm pretty confident

**Comment by ncupertino** [comment]
I will test it and then give feedback
