### ISSUE TITLE
Test ShouldSumNumbersWithTwoWindowsAndDSTTimezone is failing when in a Windows platform

### ISSUE THREAD

**Issue by leonasa** [LGouellec/kafka-streams-dotnet#38]
Description
===========
The unit test ShouldSumNumbersWithTwoWindowsAndDSTTimezone fails when running in a Windows environment.

How to reproduce
================
Run the unit test ShouldSumNumbersWithTwoWindowsAndDSTTimezone in a Windows machine/docker image

**Comment by LGouellec** [comment]
Thanks for your issue. 

Very strange, its works with my settings.
France language
Timezone Paris

What are your settings ?

**Comment by leonasa** [comment]
I was actually trying to build on github:
https://github.com/leonasa/kafka-streams-dotnet/runs/1259854403?check_suite_focus=true

I will retry later on a local windows machine.

**Comment by LGouellec** [comment]
In build ci github, it’s Linux docker container and I already saw that with Linux this test is KO. I don’t know why :( 

That’s why I add this condition in my test 
https://github.com/LGouellec/kafka-streams-dotnet/blob/94c754d2744b8e1e8be4eae6c593b9f680405f7b/test/Streamiz.Kafka.Net.Tests/Public/CustomWindowTests.cs#L132
