### ISSUE TITLE
High CPU usage, seen on Linux

### ISSUE THREAD

**Issue by varma1035** [LGouellec/kafka-streams-dotnet#43]
Description
===========
Observed high COU usage when streams starts.

How to reproduce
================

StreamBuilder builder = new StreamBuilder();
            var config = GetConfig();
builder.Stream<string, string, StringSerDes, StringSerDes>(inputTopic)
                                       .MapValues((v) => SaveAndCompare(v))
                                       .Filter((k, v) => string.IsNullOrEmpty(v) == false)
                                       .To<StringSerDes, StringSerDes>(outputTopic);

            Topology t = builder.Build();
            KafkaStream stream = new KafkaStream(t, config);
            stream.Start(cancellationToken);
            while (!cancellationToken.IsCancellationRequested)
            {
                await Task.Delay(1000, cancellationToken);
            }
            stream.Close();
            IsClosed = true;
            _logger.Info("ByHost compare is closed.");

**Comment by LGouellec** [comment]
Hi @varma1035 , 

How many threads is configured with your stream config ? Is it possible to have your stream config ? (You can discard credentials of course)

High CPU usage is just on start ? Or keep this after some minutes ? 

When you said High CPU usage, is it possible to digitize this metrics ? 100%, 50%, 25% CPU Usage ? 

How many cores your application run ? 

Thanks for yours feedbacks.

**Comment by erichnog** [comment]
Hi!

Adding to the discussion, I got a high CPU usage also on Windows.
I have a very simple stream that just prints the messages like this:

```csharp
static async System.Threading.Tasks.Task Main(string[] args)
{
    var config = new StreamConfig<StringSerDes, StringSerDes>();
    config.ApplicationId = "test-app";
    config.BootstrapServers = "localhost:9092";

    StreamBuilder builder = new StreamBuilder();
    IKStream<string, string> kStream = builder.Stream<string, string>("test-topic");

    kStream.Print(Printed<string, string>.ToOut());

    Topology t = builder.Build();
    KafkaStream stream = new KafkaStream(t, config);

    Console.CancelKeyPress += (o, e) => stream.Dispose();

    await stream.StartAsync();
}
```

Even with no messages being processed the process keep at 12% CPU usage (1 core on my machine). 

![Captura de tela 2020-12-05 203037](https://user-images.githubusercontent.com/521378/101267565-cb185d80-3738-11eb-86f1-dec0659e6f96.png)

**Comment by LGouellec** [comment]
Hi @erichnog, 

Thanks for you help ! I will try to reproduce and analyze this problem ASAP !

If you are more informations in future, please free to complete this issue.

Many thanks ;)

**Comment by LGouellec** [comment]
Hi @erichnog and  @varma1035, I use @erichnog topology found in example, I reproduced and I found a fix :)

Before fix : 
<img width="500" alt="Capture" src="https://user-images.githubusercontent.com/3295357/101336473-d1165780-387a-11eb-94fc-36f432f1a036.PNG">

After fix :
<img width="502" alt="Capture2" src="https://user-images.githubusercontent.com/3295357/101336479-d2e01b00-387a-11eb-9a1f-16066ffcc476.PNG">

**Comment by varma1035** [comment]
Is this fix available/out now? Can I download from nuget?

**Comment by LGouellec** [comment]
@varma1035, 

At time, fix is just available in develop branch.
I will publish a fix release 1.1.2 in nuget soon.

Regards,

**Comment by erichnog** [comment]
Hi @LGouellec !

I can confirm the fix on the develop branch.
Now the CPU usage is very low and the messages as printed normally.

![Captura de tela 2020-12-07 084925](https://user-images.githubusercontent.com/521378/101347774-509b2b00-3869-11eb-9cc4-980a9e4e8b07.png)

Thank you very much!

**Comment by LGouellec** [comment]
I published a new release 1.1.2 with this [fix](https://github.com/LGouellec/kafka-streams-dotnet/releases/tag/v1.1.2).

Please free to test and close this issue.

**Comment by LGouellec** [comment]
@varma1035 @erichnog Have you tried the next release ? Problem was fixed ? Can I close this issue ?

**Comment by erichnog** [comment]
Yes! 🙂
