### ISSUE TITLE
Broker: Unknown topic or partition

### ISSUE THREAD

**Issue by Janus88** [LGouellec/kafka-streams-dotnet#45]
Description
===========
I tried to run a simple sample application with a confluent cloud cluster (first kafka-streams-dotned try for me). When starting there appears a StreamsException: Unknown topic or partition.

![image](https://user-images.githubusercontent.com/8038120/102207803-e15bb180-3ece-11eb-925d-057ec06eb7f6.png)

As you can see the necessary topics do exist:
![image](https://user-images.githubusercontent.com/8038120/102207923-06e8bb00-3ecf-11eb-9130-939f38eab2d1.png)
![image](https://user-images.githubusercontent.com/8038120/102208227-6c3cac00-3ecf-11eb-9add-7c93eee000cd.png)

Perhaps there is a simple solution, but I don't have anymore ideas :-(

**Comment by LGouellec** [comment]
Hi @Janus88, I see in your configuration : 
``` csharp
config.SecurityProtocol = SecurityProtocol.SaslSsl;
```
but I didn't see certificates configuration. Are you sure your configuration is right ? 

and second, your exception throw from Confluent Kafka .Net client. 
Are you tried to consume messages from topic source with a basic consumer using [Confluent Kafka Dotnet](https://github.com/confluentinc/confluent-kafka-dotnet) package ?

**Comment by Janus88** [comment]
Yes I use the Confluent Kafka Dotnet Package as well in another project successful with the following configuration:

![image](https://user-images.githubusercontent.com/8038120/102232429-68208680-3eef-11eb-819e-c71078ea8114.png)

**Comment by Janus88** [comment]
Like in the official sample from confluent:

https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/ConfluentCloud/Program.cs

**Comment by Janus88** [comment]
I'm very sorry, I found my failure... I have to clusters, the username/password was for the other cluster. But instead of unauthorized this is the result...

**Comment by LGouellec** [comment]
Hum ok good ! Yeah I agree with you, error is not the expected error message what unauthorize happens.

**Comment by Janus88** [comment]
The strang thing was that if I changed the password, I got an unauthorized. Perhaps the API Keys are managed for all clusters but have only access to the ressources of the assigned cluster. Indeed very strange, costed me many hours the last two days...
