### ISSUE TITLE
SchemaAvroSerDes<T> is not initialized with TopologyTestDriver

### ISSUE THREAD

**Issue by fglaeser** [LGouellec/kafka-streams-dotnet#54]
Description
===========
I got  "SchemaAvroSerDes<T> is not initialized !" message after pipe a new avro message using the TopologyTestDriver. After checking the source code I saw that the `SchemaAvroSerDes.Initialize` method is nerver called.

How to reproduce
================

 ```csharp
    var config = new StreamConfig();
    config.ApplicationId = "app-test";
    config.AutoOffsetReset = AutoOffsetReset.Earliest;
    config.NumStreamThreads = 1;

    config.Acks = Acks.All;
    config.AddConsumerConfig("allow.auto.create.topics", "false");
    config.MaxTaskIdleMs = 50;

    StreamBuilder builder = new StreamBuilder();

    var ss = builder.Stream<string, Order, StringSerDes, SchemaAvroSerDes<Order>>("test-topic")
    .Peek((k, v) =>
    {
      Console.WriteLine($"Order #  {v.Number }");
    });
    Topology t = builder.Build();

    using (var driver = new TopologyTestDriver(t, config))
    {
        var inputTopic = driver.CreateInputTopic<string, Order, StringSerDes, SchemaAvroSerDes<Order>>("test-topic");
        inputTopic.PipeInput("test",  new Order { Number = "sdsdsds" } ); // <---- ERROR MESSAGE HERE
    }
```

Streamiz.Kafka.Net: 1.1.4-RC1
Kafka 2.7.0
Win 10.

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [x] Streamiz.Kafka.Net nuget version.
 - [x] Apache Kafka version.
 - [ ] Client configuration.
 - [x] Operating system.
 - [ ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
This issue is fixed. Release 1.1.4 soon
