### ISSUE TITLE
How to know if the kafka stream is ready to starting consuming

### ISSUE THREAD

**Issue by DeaThrash** [LGouellec/kafka-streams-dotnet#61]
Description
===========
Hi!
We are making use of kafka-streams-dotnet library in a dotnet with a pretty simple config:
```
var streamBuilder = new StreamBuilder();
            streamBuilder.Stream<string, byte[]>(topic)
                .Foreach((k, v) =>
                {
                    // doing some async process with the message consumed (storing to a postgres table)
                });

            var topology = streamBuilder.Build();
            var streamConfig = new StreamConfig<StringSerDes, ByteArraySerDes>
            {
                ApplicationId = "test-app",
                BootstrapServers = bootstrapServer,
                NumStreamThreads = 1
            };
            var stream = new KafkaStream(topology, streamConfig);

            Console.CancelKeyPress += (o, e) => { stream.Dispose(); };

            await stream.StartAsync();
```
We are trying to test this consumer using test containers and xunit. We are successfully creating the kafka test container but we are facing some issues when consuming messages with the stream. These tests are producing some messages and the expectation is to see the process of them being consumed, but looks like the message produced by the first test is not being consumed.

While taking a look at the code I'm seeing logs like the following one:
```
1383 [test-app-stream-thread-0] INFO Streamiz.Kafka.Net.Processors.StreamThread - stream-thread[test-app-stream-thread-0] State transition from STARTING to PARTITIONS_ASSIGNED

// other logs related to the execution of the test

1436 [test-app-stream-thread-0] INFO Streamiz.Kafka.Net.Processors.StreamThread - stream-thread[test-app-stream-thread-0] State transition from PARTITIONS_ASSIGNED to RUNNING
```
And this leads me to think that maybe this first tests is running **before** the kafka stream is actually running and ready to start consuming. Worth to mention that the following messages produced by the tests are being consumed with no problem.

Question is: does my assumption sound correct? if so, is there a way to know that the stream is ready to consume messages? I'm also new working with dotnet and would appreciate any thoughts on how to make the tests wait until the stream is ready.

Thank you in advance!

**Comment by LGouellec** [comment]
Hi @DeaThrash,

First, you need to configure your offset reset policy to : 
```csharp
config.AutoOffsetReset = Confluent.Kafka.AutoOffsetReset.Earliest;
```
This configuration allow to reset offset to minimum when you consume a topic. (Doc: [here](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html#consumerconfigs_auto.offset.reset))

Also I you want notify when your streams is running, you can make a little code like that : 
``` csharp
bool isRunningState  = false;
var timeout = TimeSpan.FromSeconds(100);
            stream.StateChanged += (old, @new) =>
            {
                if (@new.Equals(KafkaStream.State.RUNNING))
                {
                    isRunningState = true;
                }
            };
            await stream.StartAsync();
            while (!isRunningState)
            {
                Thread.Sleep(100);
                if (DateTime.Now > dt + timeout)
                {
                    break;
                }
            }

// Your stream is running with partition assigned
```

**Comment by DeaThrash** [comment]
Great! Thank you so much for the response, will try that approach.

**Comment by LGouellec** [comment]
Please feel free to close this issue if your question is done 😃
