### ISSUE TITLE
How do you use ProtobufSerializer with this library?

### ISSUE THREAD

**Issue by mmhealey1** [LGouellec/kafka-streams-dotnet#64]

**Comment by LGouellec** [comment]
Hi @mmhealey1, at time I don't propose a serializer for Protobuf. I just propose Avro Serializer which interact with Confluent Schema Registry.
Fortunately, you have a workaround :
You can implement your own ProtobufSerDes like [SchemaAvroSerDes](https://github.com/LGouellec/kafka-streams-dotnet/blob/develop/serdes/Streamiz.Kafka.Net.SchemaRegistry.SerDes.Avro/SchemaAvroSerDes.cs).

It's present in my [roadmap](https://github.com/LGouellec/kafka-streams-dotnet#todo-implementation).I don't know if it'ill be present on next release (1.2.0). If you implement your own serdes, maybe you can make a PR.

I hope I answered your question.

Regards,

**Comment by LGouellec** [comment]
PR #69 merged
