### ISSUE TITLE
Dotnet testcontainers support

### ISSUE THREAD

**Issue by LGouellec** [LGouellec/kafka-streams-dotnet#77]
Description
===========

Add some integration tests with [dotnet testcontainers library](https://github.com/HofmeisterAn/dotnet-testcontainers)

**Comment by RogerSep** [comment]
I actually have some written in my application using your library. I can upload some for you but I don't know where to put them.

**Comment by LGouellec** [comment]
I would use dotnet test container to start a real Kafka broker and write integration tests.

You can inspire these unit tests adding containers & producer/consumer assert : https://github.com/LGouellec/kafka-streams-dotnet/blob/develop/test/Streamiz.Kafka.Net.Tests/Public/KafkaStreamTests.cs

**Comment by LincolnTx** [comment]
> RogerSep
 Hello could share this with me? I'm starting write test in my application and it would be a great help
