### ISSUE TITLE
Add metrics

### ISSUE THREAD

**Issue by RogerSep** [LGouellec/kafka-streams-dotnet#81]
You have in your TODO list adding metrics which is a feature that I need.
Would you kindly give me advice on how to make this happen? I will file a pull request once I have something.

**Comment by LGouellec** [comment]
Hi,

I would expose same metrics like JAVA implementation : https://docs.confluent.io/platform/current/streams/monitoring.html

Unfortunately, .net haven't exposition mecanism like Java (jmx beans), so we need to create a layering to expose metrics.

In my imagination :
- add a new configuration property : a metrics reporter interface.
- create a third party library for each metrics reporter implementation (for example, one library for Prometheus reporter, another one for InfluxDb reporter, etc ...)
- each developer can choice your reporter in the nuget library and implementation custom one if need

Producer & Consumer .net metrics doesn't expose also. So we need to expose with same maxims like above. Unfortunately, .net name metrics and Java are not same. So we need to do a little translate before exposing : 

https://github.com/edenhill/librdkafka/blob/master/STATISTICS.md

Regards,

**Comment by LGouellec** [comment]
PR : #111 done
Will be available on 1.3.0 release
