### ISSUE TITLE
Propagating correlation id context.

### ISSUE THREAD

**Issue by RogerSep** [LGouellec/kafka-streams-dotnet#83]
Hi, do you have any advice as to how to propagate the correlation id into the logging context? Have you done it for your applications?

I would like to have my applications log a header I'm sending called `X-Correlation-Id`. This is a common thing to do for http servers and http calls to other services, but I want my kafka consumers to do it too. Is there a mechanism in this library that I can use for it?

An overview of what I'm after is:
- Get the correlation id from the message headers
- Propagate this into the logging context
- Calls to web services should get that too sent in the request headers
- Have produced messages get the correlation id header too

```
builder.Stream<string, string>("topic")
    .Peek((k, v) => Log.Debug($"Got a message! ({k}, {v})")) // Should log the correlation id
    .MapValues(v => makehttpcall(v)) // Should send the request header with the same correlation id
    .To("topic2"); // Should produce the message with the correlation id header.
```

Of course not all of these need to be solved by the library, but this library is to be used in the context of an application where observability plays a big role. Perhaps I could work on a pull request to play nicely with this feature. Let me know!

Regards.

**Comment by LGouellec** [comment]
Hi,

I'm not sure what you want to do, but a helper exist in DSL to get current metadata.

Of course, you can replace, remove header during processing and it will be persist into sink message after. 

Please feel free to check : https://github.com/LGouellec/kafka-streams-dotnet/blob/43c56d444c7b88f57f0d0005ba613a2843a585bd/test/Streamiz.Kafka.Net.Tests/Public/StreamizMetadataTests.cs#L30
